import Testing
import Foundation
@testable import ClipMenu

// The General-pane "Time interval to observe the clipboard" slider writes
// PreferenceKeys.timeInterval; the monitor must apply it (it was ignored, so
// the slider was a no-op) and clamp the slider's 0 so the poll never busy-loops.
@Suite struct PollIntervalTests {

    @Test func usesConfiguredInterval() {
        #expect(PasteboardMonitor.effectiveInterval(fromSeconds: 0.5) == .milliseconds(500))
    }

    @Test func clampsZeroToASafeFloor() {
        // 0 (slider minimum) must not become a zero-delay busy loop.
        #expect(PasteboardMonitor.effectiveInterval(fromSeconds: 0) == PasteboardMonitor.minInterval)
    }

    @Test func clampsAboveTheLegacyMaximum() {
        #expect(PasteboardMonitor.effectiveInterval(fromSeconds: 5) == PasteboardMonitor.maxInterval)
    }

    @Test func missingPreferenceUsesDefault() {
        // nil (key never set) → the default interval.
        #expect(PasteboardMonitor.effectiveInterval(fromSeconds: nil) == PasteboardMonitor.defaultInterval)
    }

    @Test func pollToleranceIsAQuarterOfTheInterval() {
        // Coalescing tolerance lets macOS batch our recurring wake-up with other
        // timers, cutting distinct wake events (energy) without changing cadence.
        #expect(PasteboardMonitor.pollTolerance(for: .milliseconds(800)) == .milliseconds(200))
        #expect(PasteboardMonitor.pollTolerance(for: PasteboardMonitor.defaultInterval)
                == PasteboardMonitor.defaultInterval / 4)
    }
}

// The frontmost-app exclusion rule (used both at snapshot time and by the
// monitor's copy-then-switch guard) must skip excluded bundle ids and no others.
@Suite struct ExcludedAppTests {

    @Test func bundleInExcludeListIsExcluded() {
        #expect(PasteboardReader.isExcluded("org.openoffice.script", in: ["org.openoffice.script"]))
    }

    @Test func bundleNotInExcludeListIsNotExcluded() {
        #expect(!PasteboardReader.isExcluded("com.apple.Safari", in: ["org.openoffice.script"]))
    }

    @Test func nilFrontmostBundleIsNotExcluded() {
        #expect(!PasteboardReader.isExcluded(nil, in: ["org.openoffice.script"]))
    }

    @Test func emptyExcludeListExcludesNothing() {
        #expect(!PasteboardReader.isExcluded("org.openoffice.script", in: []))
    }
}

// Password managers (1Password, Bitwarden, KeePassXC, Dashlane, …) mark
// clipboard writes that must not be recorded with the de facto standard
// nspasteboard.org marker types. The capture path must skip those changes.

@Suite struct PasteboardPrivacyTests {

    @Test func concealedMarkerIsDetected() {
        #expect(PasteboardReader.containsPrivacyMarker(
            ["public.utf8-plain-text", "org.nspasteboard.ConcealedType"]
        ))
    }

    @Test func transientMarkerIsDetected() {
        #expect(PasteboardReader.containsPrivacyMarker(
            ["org.nspasteboard.TransientType", "public.utf8-plain-text"]
        ))
    }

    @Test func autoGeneratedMarkerIsDetected() {
        #expect(PasteboardReader.containsPrivacyMarker(
            ["org.nspasteboard.AutoGeneratedType"]
        ))
    }

    @Test func ordinaryTypesAreNotFlagged() {
        #expect(!PasteboardReader.containsPrivacyMarker(
            ["public.utf8-plain-text", "public.rtf", "public.tiff"]
        ))
        #expect(!PasteboardReader.containsPrivacyMarker([]))
    }
}

@Suite struct ClipboardHashTests {

    @Test func differentSameLengthPDFDataHaveDifferentHashes() {
        let first = stableContentHash(
            typeNames: ["PDF"], stringValue: nil, rtfData: nil,
            pdfData: Data([0x00, 0x01, 0x02, 0x03]),
            filenames: nil, urlString: nil, imageData: nil)
        let second = stableContentHash(
            typeNames: ["PDF"], stringValue: nil, rtfData: nil,
            pdfData: Data([0x03, 0x02, 0x01, 0x00]),
            filenames: nil, urlString: nil, imageData: nil)

        #expect(first != second)
    }

    @Test func differentSameLengthImageDataHaveDifferentHashes() {
        let first = stableContentHash(
            typeNames: ["TIFF"], stringValue: nil, rtfData: nil,
            pdfData: nil, filenames: nil, urlString: nil,
            imageData: Data([0x10, 0x20, 0x30]))
        let second = stableContentHash(
            typeNames: ["TIFF"], stringValue: nil, rtfData: nil,
            pdfData: nil, filenames: nil, urlString: nil,
            imageData: Data([0x30, 0x20, 0x10]))

        #expect(first != second)
    }

    @Test func identicalBinaryDataKeepsTheSameHash() {
        let data = Data([0xaa, 0xbb, 0xcc])
        let first = stableContentHash(
            typeNames: ["RTF"], stringValue: nil, rtfData: data,
            pdfData: nil, filenames: nil, urlString: nil, imageData: nil)
        let second = stableContentHash(
            typeNames: ["RTF"], stringValue: nil, rtfData: data,
            pdfData: nil, filenames: nil, urlString: nil, imageData: nil)

        #expect(first == second)
    }
}
